### PR TITLE
Git handling renamed files

### LINKED ISSUE #1258: Clicking on a Git file-revision shows folders instead of the file contents
I'm using `opengrok-0.13-rc4` and `git version 2.9.0.windows.1`. In the web application, clicking the revision of a file in the `GitRepository` shows folders instead of the file contents. Is this issue related to how `OpenGrok` uses the `Git` options, or how `Git` is configured?

```
File.cs revision e214d6ae
tree e214d6ae:

Folder1/
Folder2/
Folder3/
```

### LINKED ISSUE #1335: Annotate partially fails with git for renamed/moved files
Steps to reproduce:

```bash
$ git init
$ touch main.c
$ nano main.c # - add some lines
$ git commit
$ mkdir moved
$ mv main.c moved/
$ git commit
$ nano moved/main.c # - change/add some other lines
$ git commit
```

Now index and navigate to the file annotation. The old revisions aren't colored (but they should be since last 10 revisions get their color). The tooltip is empty.

On the picture the revisions on the top are the old ones (before moving), the second revisions are the one after the move:
screenshot from 2017-01-20 12-48-05

### PR DESCRIPTION
**Pull request by tulinkry**
This should fix #1335 and it might fix #1258.
Implements #794

There should be no harm with this. If anything does not work, it will work like it did before - no renamed files tracking.

### CODE REVIEW

File: src/org/opensolaris/opengrok/history/GitRepository.java [hunk 1]
```diff
@@ -252,11 +246,154 @@ public InputStream getHistoryGet(String parent, String basename, String rev) {
...
+    }
+
+    @Override
+    public InputStream getHistoryGet(String parent, String basename, String rev) {
+        String fullpath;
+        try {
+            fullpath = new File(parent, basename).getCanonicalPath();
+        } catch (IOException exp) {
+            LOGGER.log(Level.SEVERE,
+                    "Failed to get canonical path: {0}", exp.getClass().toString());
```
Comment (vladak) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: is `parent` + `basename` part of the exception string here ?

File: src/org/opensolaris/opengrok/history/GitRepository.java [hunk 2]
```diff
@@ -252,11 +246,154 @@ public InputStream getHistoryGet(String parent, String basename, String rev) {
...
+             * If we failed to get the contents it might be that the file was
+             * renamed so we need to find its original name in that revision
+             * and retry with the original name.
+             */
+            String origpath;
+            try {
+                origpath = findOriginalName(fullpath, rev);
+            } catch (IOException exp) {
+                LOGGER.log(Level.SEVERE,
+                        "Failed to get original revision: {0}",
```
Comment (vladak) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: ditto

File: src/org/opensolaris/opengrok/history/GitRepository.java [hunk 3]
```diff
@@ -252,11 +246,154 @@ public InputStream getHistoryGet(String parent, String basename, String rev) {
...
+     * to:<br>
+     * moved/renamed.c => moved/renamed2.c (100%)<br>
+     *
+     * @param renamedFile the string to expand
+     * @return normalized string
+     */
+    protected String expandGitRenamedOutput(String renamedFile) {
+        // the pattern should cover format like this:
+        // moved/{renamed.c => renamed2.c} (100%)
+        Pattern pattern = Pattern.compile("\\s*([^\\{]+)\\s*\\{\\s*(.+?)\\s+=>\\s+([^\\}]+)\\s*\\}(.*)");
```
Comment (vladak) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: catch `PatternSyntaxException` exception just to be sure ?

File: src/org/opensolaris/opengrok/history/GitRepository.java [hunk 4]
```diff
@@ -252,11 +246,154 @@ public InputStream getHistoryGet(String parent, String basename, String rev) {
...
+                        if (split.length < 2) {
+                            throw new IOException(
+                                    String.format(
+                                            "Invalid format of the git output. Expected "
+                                            + "\"file => otherfile\" but got \"{}\"", line));
+                        }
+                        file = split[0];
+                    }
+
+                    if (rev.equals(changeset)) {
```
Comment (vladak) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: not sure how this is supposed work given the same piece of code on lines 360-362

File: src/org/opensolaris/opengrok/history/GitRepository.java [hunk 5]
```diff
@@ -252,11 +246,154 @@ public InputStream getHistoryGet(String parent, String basename, String rev) {
...
+                    }
+
+                    if (line.startsWith(" rename ")) {
+                        line = line.replace(" rename ", "");
+                        line = expandGitRenamedOutput(line);
+                        String[] split = line.split(" => ");
+                        if (split.length < 2) {
+                            throw new IOException(
+                                    String.format(
+                                            "Invalid format of the git output. Expected "
```
Comment (vladak) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: add more info about the file path

File: test/org/opensolaris/opengrok/history/GitRepositoryTest.java [hunk 6]
```diff
@@ -158,4 +163,236 @@ public void testDateFormats() {
             }
         }
     }
+
+    @Test
+    public void testRenamedFiles() throws Exception {
+        String[][] tests = new String[][]{
+            {"moved/renamed2.c", "67dfbe26", "moved/renamed2.c"},
```
Comment (vladak) [inline test/org/opensolaris/opengrok/history/GitRepositoryTest.java]: what about testing renames across distinct directories ?

File: src/org/opensolaris/opengrok/history/GitRepository.java [hunk 7]
```diff
@@ -197,47 +189,49 @@ Reader newLogReader(InputStream input) throws IOException {
...
-                }
-            }
-            if (error) {
-                process.destroy();
-                String path = getCorrectPath(filename, rev);
-                argv[2] = rev + ":" + path;
-                process = Runtime.getRuntime().exec(argv, null, directory);
-                in = process.getInputStream();
+            ByteArrayOutputStream out = new ByteArrayOutputStream();
+            byte[] buffer = new byte[32 * 1024];
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: I don't think so. We've had the same buffer size in MercurialRepository for a long time

File: src/org/opensolaris/opengrok/history/GitHistoryParser.java [hunk 8]
```diff
@@ -142,36 +140,45 @@ private void process(BufferedReader in) throws IOException {
         if (entry != null) {
             entries.add(entry);
         }
-
-        history.setHistoryEntries(entries);
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitHistoryParser.java]: because the history is now created as a return value directly
```java
return new History(entries, parser.getRenamedFiles());
```

File: src/org/opensolaris/opengrok/history/GitHistoryParser.java [hunk 9]
```diff
@@ -184,6 +191,60 @@ History parse(File file, Repository repos, String sinceRevision) throws HistoryE
...
+    /**
+     * Class for handling renamed files stream.
+     */
+    private class RenamedFilesParser implements Executor.StreamHandler {
+
+        private final List<String> renamedFiles = new ArrayList<>();
+
+        @Override
+        public void processStream(InputStream input) throws IOException {
+            /*
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitHistoryParser.java]: done

File: src/org/opensolaris/opengrok/history/GitRepository.java [hunk 10]
```diff
@@ -170,11 +125,48 @@ Executor getHistoryLogExecutor(final File file, String sinceRevision)
...
+            cmd.add(filename);
+        }
+
+        return new Executor(cmd, new File(getDirectoryName()), sinceRevision != null);
+    }
+
+    Executor getRenamedFilesExecutor(final File file, String sinceRevision) throws IOException {
+        String abs = file.getCanonicalPath();
+        String filename = "";
+        if (abs.length() > directoryName.length()) {
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: not basename, but a relative path to the file in the repository

File: src/org/opensolaris/opengrok/history/GitRepository.java [hunk 11]
```diff
@@ -170,11 +125,48 @@ Executor getHistoryLogExecutor(final File file, String sinceRevision)
...
+            filename = abs.substring(directoryName.length() + 1);
+        }
+
+        ensureCommand(CMD_PROPERTY_KEY, CMD_FALLBACK);
+        List<String> cmd = new ArrayList<>();
+        cmd.add(RepoCommand);
+        cmd.add("log");
+        cmd.add("-M8"); // similarity 80%
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: The default value is 50% so I pushed that up to 80%. 100% is to much I think...one can change the location of the file while changing some lines

File: src/org/opensolaris/opengrok/history/GitRepository.java [hunk 12]
```diff
@@ -170,11 +125,48 @@ Executor getHistoryLogExecutor(final File file, String sinceRevision)
...
+
+        if (file.isFile()) {
+            cmd.add("--follow");
+        }
+
         if (sinceRevision != null) {
             cmd.add(sinceRevision + "..");
         }
 
         if (filename.length() > 0) {
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: I modified the lines commented in [this comment](https://github.com/OpenGrok/OpenGrok/pull/1345#discussion_r97753146) and moved them here.

It's not really check for a file but anything under the git repository (not the repository itself). The following git command will throw an error if the path does not exist.

File: src/org/opensolaris/opengrok/history/GitRepository.java [hunk 13]
```diff
@@ -197,47 +189,49 @@ Reader newLogReader(InputStream input) throws IOException {
...
         File directory = new File(directoryName);
-
-        ByteArrayOutputStream output = new ByteArrayOutputStream();
-        byte[] buffer = new byte[8192];
-
         Process process = null;
+
         try {
-            String filename = (new File(parent, basename)).getCanonicalPath()
+            String filename = (new File(parent, fullpath)).getCanonicalPath()
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: yes

File: src/org/opensolaris/opengrok/history/GitRepository.java (hunk 1 above)
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: now is

File: src/org/opensolaris/opengrok/history/GitRepository.java (hunk 2 above)
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: now is

File: src/org/opensolaris/opengrok/history/GitRepository.java (hunk 3 above)
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: the pattern is hardcoded so the exception can't occur

File: src/org/opensolaris/opengrok/history/GitRepository.java (hunk 5 above)
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: done

File: src/org/opensolaris/opengrok/history/GitRepository.java (hunk 4 above)
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: mistake. removed

File: src/org/opensolaris/opengrok/history/GitHistoryParser.java [hunk 14]
```diff
@@ -142,36 +140,45 @@ private void process(BufferedReader in) throws IOException {
...
+        RenamedFilesParser parser = new RenamedFilesParser();
         try {
             Executor executor = repository.getHistoryLogExecutor(file, sinceRevision);
             int status = executor.exec(true, this);
 
             if (status != 0) {
-                throw new HistoryException("Failed to get history for: \"" +
-                        file.getAbsolutePath() + "\" Exit code: " + status);
+                throw new HistoryException("Failed to get history for: \""
+                        + file.getAbsolutePath() + "\" Exit code: " + status);
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitHistoryParser.java]: This is what I get when I autoformat in netbeans with default settings. I changed those lines anyway to use `String.format` and not string composition.

File: test/org/opensolaris/opengrok/history/GitRepositoryTest.java (hunk 6 above)
Comment (tulinkry) [inline test/org/opensolaris/opengrok/history/GitRepositoryTest.java]: I added a test case

File: src/org/opensolaris/opengrok/history/GitHistoryParser.java [hunk 15]
```diff
@@ -184,6 +191,60 @@ History parse(File file, Repository repos, String sinceRevision) throws HistoryE
...
+             * A foo2.f
+             * A main.c
+             *
+             */
+            RuntimeEnvironment env = RuntimeEnvironment.getInstance();
+
+            try (BufferedReader in = new BufferedReader(new InputStreamReader(input))) {
+                String line;
+                while ((line = in.readLine()) != null) {
+                    if (line.startsWith("R")) {
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitHistoryParser.java]: done

File: src/org/opensolaris/opengrok/history/GitRepository.java (hunk 3 above)
Comment (vladak) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: unless the compiler changes.. better to catch it

Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/GitRepository.java]: I forgot to mention that I changed the command to obtain more predictable output format (without these `{, }` constructs. So this method is no longer available :-)

**Comment by vladak** [comment]
Could you do some basic perf. measurements for some Git repo with renames ? Also, you should see standalone `git log` processes to be forked for the renamed files.

**Comment by tulinkry** [comment]
Ok. I created a small testing repo and did some renames. These commands I executed to create the repository:

[also download repo.txt](https://github.com/OpenGrok/OpenGrok/files/735217/repo.txt)
```bash
mkdir renamed
cd renamed/
mkdir 1
mkdir 2
mkdir 3
tr -dc A-Za-z0-9 </dev/urandom | head -c 20kB > 1/file.txt
tr -dc A-Za-z0-9 </dev/urandom | head -c 25kB > 2/file.txt
tr -dc A-Za-z0-9 </dev/urandom | head -c 30kB > 3/file.txt
mkdir -p {1,2,3}/{1,2,3}
tr -dc A-Za-z0-9 </dev/urandom | head -c 30kB > 1/1/file.txt
tr -dc A-Za-z0-9 </dev/urandom | head -c 30kB > 1/2/file.txt
tr -dc A-Za-z0-9 </dev/urandom | head -c 30kB > 1/3/file.txt
tr -dc A-Za-z0-9 </dev/urandom | head -c 30kB > 2/1/file.txt
tr -dc A-Za-z0-9 </dev/urandom | head -c 30kB > 2/2/file.txt
tr -dc A-Za-z0-9 </dev/urandom | head -c 30kB > 2/3/file.txt
tr -dc A-Za-z0-9 </dev/urandom | head -c 30kB > 3/1/file.txt
tr -dc A-Za-z0-9 </dev/urandom | head -c 30kB > 3/2/file.txt
tr -dc A-Za-z0-9 </dev/urandom | head -c 30kB > 3/3/file.txt
git init
git add 1/
git commit -m "first"
git add 2/1/
git commit -m "second"
git mv 1 4
git add 1
git add 1/
git add 4/
git commit -m "first rename"
git add 2/2
git commit -m "third"
git add 3
git commit "fourth"
git commit -m "fourth"
mkdir 1
mv 4/1/file.txt 1/
git add 4
git add 1
git commit -m "second rename"
git add 2/3
git commit -m "fifth"
mv 3/3/file.txt .
cat file.txt | head -c 20Kb > tmp && cp tmp file.txt && rm tmp
git add 3
git add file.txt
git commit -m "third rename"
git add 2/
git commit -m "sixth"
git log
git status
git commit
```

Then I ran the index process from scratch for current master (without) and this pr (with).
```bash
$ time strace -f 2>&1 ./OpenGrok index | egrep "fork|exec.*" > exec-without.log

real	0m2.776s
user	0m2.740s
sys	0m0.960s
$ time strace -f 2>&1 ./OpenGrok index | egrep "fork|exec.*" > exec-with.log

real	0m2.335s
user	0m2.548s
sys	0m1.092s
```
I did that several times, once the with version had like 5s. Most of the time it was same.

These are the outputs:

[download exec-without.txt](https://github.com/OpenGrok/OpenGrok/files/735219/exec-without.txt)
```plain
[pid 16355] execve(["--help"])
[pid 16357] execve(["remote", "-v"])
[pid 16358] execve(["branch"])
[pid 16360] execve(["log", "-1", "--pretty=%cd: %h %an %s", "--date=rfc"])
[pid 16363] execve(["--help"])
[pid 16365] execve(["remote", "-v"])
[pid 16366] execve(["branch"])
[pid 16368] execve(["log", "-1", "--pretty=%cd: %h %an %s", "--date=rfc"])
[pid 16372] execve(["log", "--abbrev-commit", "--abbrev=8", "--name-only", "--pretty=fuller", "--date=rfc"])
[pid 16376] execve(["log", "--abbrev-commit", "--abbrev=8", "--name-only", "--pretty=fuller", "--date=rfc", "dbe628c0.."])
```

[download exec-with.txt](https://github.com/OpenGrok/OpenGrok/files/735218/exec-with.txt)
```plain
[pid 16648] execve(["--help"]
[pid 16650] execve(["remote", "-v"]
[pid 16651] execve(["branch"]
[pid 16653] execve(["log", "-1", "--pretty=%cd: %h %an %s", "--date=rfc"])
[pid 16656] execve(["--help"])
[pid 16658] execve(["remote", "-v"])
[pid 16659] execve(["branch"])
[pid 16661] execve(["log", "-1", "--pretty=%cd: %h %an %s", "--date=rfc"])
[pid 16665] execve(["log", "--abbrev-commit", "--abbrev=8", "--name-only", "--pretty=fuller", "--date=rfc"])
[pid 16668] execve(["log", "--find-renames=8", "--summary", "--abbrev=8", "--name-status", "--oneline"])
[pid 16675] execve(["log", "--abbrev-commit", "--abbrev=8", "--name-only", "--pretty=fuller", "--date=rfc", "--follow", "4/2/file.txt"])
[pid 16679] execve(["log", "--abbrev-commit", "--abbrev=8", "--name-only", "--pretty=fuller", "--date=rfc", "--follow", "file.txt"], [/
[pid 16680] execve(["log", "--abbrev-commit", "--abbrev=8", "--name-only", "--pretty=fuller", "--date=rfc", "--follow", "4/3/file.txt"], 
[pid 16686] execve(["log", "--abbrev-commit", "--abbrev=8", "--name-only", "--pretty=fuller", "--date=rfc", "--follow", "1/file.txt"], 
[pid 16688] execve(["log", "--find-renames=8", "--summary", "--abbrev=8", "--name-status", "--oneline", "--follow", "--", "4/3/file.txt"], 
[pid 16692] execve(["log", "--find-renames=8", "--summary", "--abbrev=8", "--name-status", "--oneline", "--follow", "--", "4/2/file.txt"], 
[pid 16697] execve(["log", "--find-renames=8", "--summary", "--abbrev=8", "--name-status", "--oneline", "--follow", "--", "file.txt"], 
[pid 16699] execve(["log", "--find-renames=8", "--summary", "--abbrev=8", "--name-status", "--oneline", "--follow", "--", "1/file.txt"], 
[pid 16703] execve(["log", "--abbrev-commit", "--abbrev=8", "--name-only", "--pretty=fuller", "--date=rfc", "dbe628c0.."])
[pid 16706] execve(["log", "--find-renames=8", "--summary", "--abbrev=8", "--name-status", "--oneline", "dbe628c0.."])
```

It's clearly visible that there is one extra git command for finding renamed files. All of the renamed files have their dedicated call to git log command to find their renamed history.

**Comment by tulinkry** [comment]
And the test is failing because of old git in travis. I'll try to fix this.

File: opengrok-indexer/build.xml [hunk 16]
```diff
@@ -121,7 +121,7 @@ Copyright (c) 2007, 2016, Oracle and/or its affiliates. All rights reserved.
               defaultexcludes="no"/>
         <zip destfile="${build.test.classes.dir}/org/opensolaris/opengrok/history/repositories.zip" 
                 basedir="${test.repositories}"
-                excludes="mercurial/hg/**, mercurial/hgignore, git/git"
+                excludes="mercurial/hg/**, mercurial/hgignore, git/git/**"
```
Comment (tulinkry) [inline opengrok-indexer/build.xml]: For me the compiled test-classes still contained the both git and .git directory which caused a null revision error for getting annotations from the git repository (as they aren't tracked by git but still are in the repository).

This exact same line is in the root build.xml with these `**` at the end.
