### PR TITLE
make the matching in Filter class more predictable

### LINKED ISSUE #1015: Git repositories not indexed if directory name contains .git
Hi,
We have a setup where both SVN and GIT repositories are fetched.
While SVN repositories are well indexed and visible on the web page, GIT repositories seems to be indexed but remain invisible.  
  
In the logs, I can see:  
```
Oct 27, 2015 8:22:02 AM org.opensolaris.opengrok.util.Executor exec
FINE: Executing command [/opt/tools/git-active/bin/git, --help] in directory /opt/tools/scripts
Oct 27, 2015 8:22:02 AM org.opensolaris.opengrok.util.Executor exec
FINE: Finished command [/opt/tools/git-active/bin/git, --help] in directory /opt/tools/scripts
Oct 27, 2015 8:22:02 AM org.opensolaris.opengrok.util.Executor exec
FINE: Executing command [/opt/tools/subversion-active/bin/svn, --help] in directory /opt/tools/scripts
Oct 27, 2015 8:22:02 AM org.opensolaris.opengrok.util.Executor exec
FINE: Finished command [/opt/tools/subversion-active/bin/svn, --help] in directory /opt/tools/scripts

[...]

Oct 27, 2015 8:22:14 AM org.opensolaris.opengrok.util.Executor exec
FINE: Finished command [/opt/tools/subversion-active/bin/svn, info, --xml] in directory /appl/itrf/opengrok/src/whaeversvnproject
Oct 27, 2015 8:22:14 AM org.opensolaris.opengrok.history.HistoryGuru addRepositories
CONFIG: Adding <org.opensolaris.opengrok.history.SubversionRepository> repository: </appl/itrf/opengrok/src/whaeversvnproject>
Oct 27, 2015 8:22:14 AM org.opensolaris.opengrok.util.Executor exec
FINE: Executing command [/opt/tools/git-active/bin/git, --help] in directory /opt/tools/scripts
Oct 27, 2015 8:22:14 AM org.opensolaris.opengrok.util.Executor exec
FINE: Finished command [/opt/tools/git-active/bin/git, --help] in directory /opt/tools/scripts
Oct 27, 2015 8:22:14 AM org.opensolaris.opengrok.history.HistoryGuru addRepositories
CONFIG: Adding <org.opensolaris.opengrok.history.GitRepository> repository: </appl/itrf/opengrok/src/whaevergitproject.git>
Oct 27, 2015 8:22:14 AM org.opensolaris.opengrok.util.Executor exec

[...]

Oct 27, 2015 8:22:41 AM org.opensolaris.opengrok.util.Executor exec
FINE: Finished command [/opt/tools/subversion-active/bin/svn, log, --trust-server-cert, --non-interactive, --xml, -v, -r, BASE:675] in directory /appl/itrf/opengrok/src/whaeversvnproject
Oct 27, 2015 8:22:41 AM org.opensolaris.opengrok.util.Statistics report
INFO: Done historycache for /appl/itrf/opengrok/src/whaeversvnproject (took 24 ms)
Oct 27, 2015 8:22:41 AM org.opensolaris.opengrok.history.HistoryGuru createCache
INFO: Creating historycache for /appl/itrf/opengrok/src/whaevergitproject.git (GitRepository)
Oct 27, 2015 8:22:41 AM org.opensolaris.opengrok.util.Executor exec
FINE: Executing command [/opt/tools/git-active/bin/git, log, --abbrev-commit, --abbrev=8, --name-only, --pretty=fuller, ac891a28..] in directory /appl/itrf/opengrok/src/whaevergitproject.git
Oct 27, 2015 8:22:41 AM org.opensolaris.opengrok.util.Executor exec
```  

I noticed openGrok append ```..``` at the end of the revision number.  
On command line, if run  
``` /opt/tools/git-active/bin/git log --abbrev-commit --abbrev=8 --name-only --pretty=fuller ac891a28.. ``` then nothing is displayed  
but if i run ``` /opt/tools/git-active/bin/git log --abbrev-commit --abbrev=8 --name-only --pretty=fuller ac891a28 ``` (without ```..```) then I can see the history.

According to git documentation, ```git log``` supports what is describes in "revision range" section (https://git-scm.com/docs/gitrevisions).
In this page, the only occurence of ```..``` is with 2 revisions: ```r1..r2```

Am I doing something wrong or is it a bug in the Git indexer ?

Thanks

### PR DESCRIPTION
**Pull request by vladak**
fixes #1015

### CODE REVIEW

File: test/org/opensolaris/opengrok/index/IgnoredNamesTest.java [hunk 1]
```diff
@@ -71,6 +71,10 @@ public void testIgnoredPatterns() {
         assertFalse(instance.ignore("usr/src/foo/bar/usr.lib/main.c"));
         assertFalse(instance.ignore("usr/src/foo/bar/usr.lib"));
 
+        /* Test handling of special directories. */
+        assertTrue(instance.ignore("usr/src/.git"));
+        assertFalse(instance.ignore("usr/src/foo.git"));
+
```
Comment (tarzanek) [inline test/org/opensolaris/opengrok/index/IgnoredNamesTest.java]: can we add a test where only FILE .repo will be ignored
but path which has .repo in it won't?

**Comment by tarzanek** [comment]
after the test is added, please merge

File: test/org/opensolaris/opengrok/index/IgnoredNamesTest.java (hunk 1 above)
Comment (vladak) [inline test/org/opensolaris/opengrok/index/IgnoredNamesTest.java]: added a test but with `.git`
