### PR TITLE
better RCS repository detection

### LINKED ISSUE #1458: smarter detection of RCS repository
Hi,

The links History and Annotate are no more available on our OpenGrok service :-(

OpenGrok: 0.12.1.6, Git 1.9.1, Java 1.8_121, Tomcat 7.0.75
When indexing, config used is:
export IGNORE_PATTERNS="-i *.bin -i *.gz -i *.rpt -i *.tar -i *.zip -i *.class -i *.bz2 -i *.7z -i *.tgz -i *.exe -i *.jar -i *.war"
export JAVA_OPTS="$JAVA_OPTS -Xmx12g -d64 -server"
export OPENGROK_FLUSH_RAM_BUFFER_SIZE="-m 256"
export OPENGROK_INSTANCE_BASE=$OPENGROK_VAR
export OPENGROK_SCAN_DEPTH=2
export OPENGROK_VERBOSE=true
export OPENGROK_WEBAPP_CONTEXT=grok
export OPENGROK_VAR=/srv/opengrok-var  (which is linked from /var/opengrok)

Sources are into /srv/opengrok-src/git. Link src -> /srv/opengrok-src/git exists in $OPENGROK_VAR.

In the confiuration.xml, I can see this part:
`<void property="repositories">`
`   <void method="add">`
`    <object class="org.opensolaris.opengrok.history.RepositoryInfo">`
`     <void property="directoryName">`
`      <string>/srv/opengrok-src/git</string>`
`     </void>`
`     <void property="type">`
`      <string>RCS</string>`
`     </void>`
`    </object>`
`   </void>`
`  </void>`

Why this RCS value wheras all my repos are Git repos ?

It is linked to what I can see in the log:
Loading the default instance configuration ...
02:54:21 FINE: Installing default uncaught exception handler
Logging filehandler pattern: /srv/opengrok-var/log/opengrok%g.%u.log
02:54:22 INFO: Scanning for repositories...
02:54:22 INFO: done invalidating repositories (took 0)
02:54:22 INFO: Done scanning for repositories (0s)
02:54:22 INFO: Writing configuration to /srv/opengrok-var/etc/configuration.xml
02:54:22 INFO: Done...
02:54:22 INFO: Generating history cache for all repositories ...
02:54:22 INFO: Creating historycache for 1 repositories
02:54:22 INFO: Creating historycache for /srv/opengrok-src/git (RCSRepository)
02:54:22 INFO: Skipping creation of history cache for /srv/opengrok-src/git, since retrieval of history for directories is not implemented for this repository type.
02:54:22 INFO: Done historycache for /srv/opengrok-src/git (took 1 ms)
02:54:22 INFO: Done historycache for all repositories (took 23 ms)
02:54:22 INFO: Done...
02:54:22 INFO: Starting indexing
...

Setup has not changed.  I had not this before. I can not understand why historycache is no more updated and links not available.

Could you help me fiure out what happens ?

### PR DESCRIPTION
**Pull request by vladak**
fixes #1458

### CODE REVIEW

File: src/org/opensolaris/opengrok/history/RCSRepository.java [hunk 1]
```diff
@@ -127,7 +128,23 @@ void update() throws IOException {
...
+        if (!rcsDir.isDirectory()) {
+            return false;
+        }
+
+        // If there is at least one entry with the ',v' suffix,
+        // consider this a RCS repository.
+        String[] list = rcsDir.list(new FilenameFilter() {
+            @Override
+            public boolean accept(File dir, String name) {
+                // Technically we should check whether the entry is a file
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/RCSRepository.java]: So why not use listFiles?

File: src/org/opensolaris/opengrok/history/RCSRepository.java [hunk 2]
```diff
@@ -127,7 +128,23 @@ void update() throws IOException {
...
+                // however this would incur additional I/O. The pattern
+                // should be enough.
+                return name.matches(".*,v");
+            }
+        });
+
+        return (list.length > 0);
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/RCSRepository.java]: I guess the possible NPE here is solved with the if on L131 `if (!rcsDir.isDirectory()) {`?

File: test/org/opensolaris/opengrok/condition/RepositoryInstalled.java [hunk 3]
```diff
@@ -27,6 +27,7 @@
 import org.opensolaris.opengrok.history.GitRepository;
 import org.opensolaris.opengrok.history.MercurialRepository;
 import org.opensolaris.opengrok.history.PerforceRepository;
+import org.opensolaris.opengrok.history.RCSRepository;
```
Comment (tulinkry) [inline test/org/opensolaris/opengrok/condition/RepositoryInstalled.java]: copyright

File: src/org/opensolaris/opengrok/history/RCSRepository.java [hunk 4]
```diff
@@ -24,6 +24,7 @@
 package org.opensolaris.opengrok.history;
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/RCSRepository.java]: copyright

Comment (vladak) [inline src/org/opensolaris/opengrok/history/RCSRepository.java]: fixed

File: src/org/opensolaris/opengrok/history/RCSRepository.java (hunk 1 above)
Comment (vladak) [inline src/org/opensolaris/opengrok/history/RCSRepository.java]: I think the differences between list() and listFiles() are:
  - return type (String vs. File)
  - listFiles() does not  get "the directory itself and the directory's parent directory"

So, listFiles() will not help much and would likely incur higher overhead.

File: test/org/opensolaris/opengrok/condition/RepositoryInstalled.java (hunk 3 above)
Comment (vladak) [inline test/org/opensolaris/opengrok/condition/RepositoryInstalled.java]: fixed

File: src/org/opensolaris/opengrok/history/RCSRepository.java (hunk 2 above)
Comment (vladak) [inline src/org/opensolaris/opengrok/history/RCSRepository.java]: yes. JavaDoc says: "If this abstract pathname does not denote a directory, then this method returns null. Otherwise an array of strings is returned, one for each file or directory in the directory."

File: src/org/opensolaris/opengrok/history/RCSRepository.java (hunk 1 above)
Comment (vladak) [inline src/org/opensolaris/opengrok/history/RCSRepository.java]: Actually, list() behaves the same as listFiles() in terms of the entries.

Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/RCSRepository.java]: ok

File: src/org/opensolaris/opengrok/history/RCSRepository.java (hunk 2 above)
Comment (tulinkry) [inline src/org/opensolaris/opengrok/history/RCSRepository.java]: ok

**Comment by tulinkry** [comment]
Ok feel free to merge
