### PR TITLE
check project name exactly in Project.getByName()

### LINKED ISSUE #1541: Project.getByName() needs to perform exact check of project name
Let's assume that `foo` and `bar` are valid project names. If the following URL is constructed:

```
https://grok/source/search?project=foo/bar&q=foo&defs=&refs=&path=&hist=&type=
```

this results in 2 exceptions:

```
 org.apache.lucene.index.IndexNotFoundException: no segments* file found in MMapDirectory@/opengrok-1.0/data/index/foo/bar lockFactory=org.apache.lucene.store.NativeFSLockFactory@49cd9676: files: 
[]
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:687)
        at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:77)
        at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
        at org.apache.lucene.search.SearcherManager.<init>(SearcherManager.java:125)
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.getIndexSearcher(RuntimeEnvironment.java:1916)
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.getMultiReader(RuntimeEnvironment.java:1981)
        at org.opensolaris.opengrok.web.SearchHelper.prepareExec(SearchHelper.java:261)
        at org.apache.jsp.search_jsp._jspService(search_jsp.java:250)
...

21-Apr-2017 14:19:18.039 SEVERE [http-nio-8888-exec-5] org.opensolaris.opengrok.configuration.RuntimeEnvironment.getMultiReader cannot get IndexReader for project foo/bar
 java.lang.NullPointerException
        at org.opensolaris.opengrok.configuration.RuntimeEnvironment.getMultiReader(RuntimeEnvironment.java:1982)
        at org.opensolaris.opengrok.web.SearchHelper.prepareExec(SearchHelper.java:261)
        at org.apache.jsp.search_jsp._jspService(search_jsp.java:250)
...
```

The correct URL is

```
https://grok/source/search?project=foo&project=bar&q=foo&defs=&refs=&path=&hist=&type=
```

The project parameters should be checked against list of projects before passing them to `searchHelper`.

### PR DESCRIPTION
**Pull request by vladak**
fixes #1541

### CODE REVIEW

File: src/org/opensolaris/opengrok/configuration/Project.java [hunk 1]
```diff
@@ -215,16 +215,15 @@ public static Project getProject(File file) {
      * @return project that fits the name
      */
     public static Project getByName(String name) {
-        Project ret = null;
         RuntimeEnvironment env = RuntimeEnvironment.getInstance();
         if (env.hasProjects()) {
             for (Project proj : env.getProjects()) {
-                if (name.indexOf(proj.getName()) == 0) {
-                    ret = proj;
+                if (name.equals(proj.getName())) {
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/Project.java]: Actually if there is this change, the container type can be finally changed from `List` to `Set (TreeSet)` which will cause ultra speedup for this lookup.

Comment (vladak) [inline src/org/opensolaris/opengrok/configuration/Project.java]: You probably mean `HashMap<String,Project>` ? The `getByName()` method needs to search according to `name` and return `Project` object.

File: src/org/opensolaris/opengrok/index/Indexer.java [hunk 2]
```diff
@@ -726,23 +726,6 @@ public void prepareIndexer(RuntimeEnvironment env,
                     projects.add(p);
                 }
             }
-
-            // The projects should be sorted...
-            Collections.sort(projects, new Comparator<Project>() {
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/index/Indexer.java]: why isn't this necessary?

File: src/org/opensolaris/opengrok/configuration/Configuration.java [hunk 3]
```diff
@@ -92,7 +92,7 @@
      */
     private boolean authorizationWatchdogEnabled;
     private List<AuthorizationCheck> pluginConfiguration;
-    private List<Project> projects;
+    private HashSet<Project> projects;
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/Configuration.java]: use supertype `Set`

File: src/org/opensolaris/opengrok/configuration/Configuration.java [hunk 4]
```diff
@@ -490,11 +490,11 @@ public void setHandleHistoryOfRenamedFiles(boolean enable) {
         this.handleHistoryOfRenamedFiles = enable;
     }
 
-    public List<Project> getProjects() {
+    public HashSet<Project> getProjects() {
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/Configuration.java]: use supertype `Set`

File: src/org/opensolaris/opengrok/configuration/Configuration.java [hunk 5]
```diff
@@ -490,11 +490,11 @@ public void setHandleHistoryOfRenamedFiles(boolean enable) {
...
         return projects;
     }
 
-    public void setProjects(List<Project> projects) {
+    public void setProjects(HashSet<Project> projects) {
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/Configuration.java]: use supertype `Set`

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java [hunk 6]
```diff
@@ -98,6 +98,7 @@
 import static java.nio.file.StandardWatchEventKinds.ENTRY_CREATE;
 import static java.nio.file.StandardWatchEventKinds.ENTRY_DELETE;
 import static java.nio.file.StandardWatchEventKinds.ENTRY_MODIFY;
+import java.util.HashSet;
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: did nb order the imports in this manner? I thought always that static imports must follow normal imports

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java [hunk 7]
```diff
@@ -409,7 +410,7 @@ public boolean hasProjects() {
      *
      * @return a list containing all of the projects (may be null)
      */
-    public List<Project> getProjects() {
+    public HashSet<Project> getProjects() {
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: use supertype `Set`

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java [hunk 8]
```diff
@@ -409,7 +410,7 @@ public boolean hasProjects() {
      *
      * @return a list containing all of the projects (may be null)
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: returning set not list

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java [hunk 9]
```diff
@@ -428,7 +429,7 @@ public boolean hasProjects() {
      *
      * @param projects the list of projects to use
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: set

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java [hunk 10]
```diff
@@ -428,7 +429,7 @@ public boolean hasProjects() {
...
      */
-    public void setProjects(List<Project> projects) {
+    public void setProjects(HashSet<Project> projects) {
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: use supertype `Set`

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java [hunk 11]
```diff
@@ -1213,7 +1214,7 @@ private void generateProjectRepositoriesMap() throws IOException {
     /**
      * Classifies projects and puts them in their groups.
      */
-    private void populateGroups(Set<Group> groups, List<Project> projects) {
+    private void populateGroups(Set<Group> groups, HashSet<Project> projects) {
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: use supertype `Set`

File: src/org/opensolaris/opengrok/search/SearchEngine.java [hunk 12]
```diff
@@ -209,7 +209,7 @@ private void searchSingleDatabase(File root, boolean paging) throws IOException
      * @param root list of projects to search
      * @throws IOException
      */
-    private void searchMultiDatabase(List<Project> root, boolean paging) throws IOException {
+    private void searchMultiDatabase(HashSet<Project> root, boolean paging) throws IOException {
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/search/SearchEngine.java]: use supertype `Set`

File: src/org/opensolaris/opengrok/search/SearchEngine.java [hunk 13]
```diff
@@ -258,7 +258,7 @@ public String getQuery() {
     public int search(HttpServletRequest req, String... projectNames) {
         ProjectHelper pHelper = PageConfig.get(req).getProjectHelper();
         Set<Project> projects = pHelper.getAllProjects();
-        List<Project> filteredProjects = new ArrayList<Project>();
+        HashSet<Project> filteredProjects = new HashSet<Project>();
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/search/SearchEngine.java]: use supertype `Set`

File: src/org/opensolaris/opengrok/search/SearchEngine.java [hunk 14]
```diff
@@ -325,7 +325,7 @@ public int search() {
      *
      * @return The number of hits
      */
-    private int search(List<Project> projects, File root) {
+    private int search(HashSet<Project> projects, File root) {
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/search/SearchEngine.java]: use supertype `Set`

File: src/org/opensolaris/opengrok/web/PageConfig.java [hunk 15]
```diff
@@ -819,12 +820,17 @@ private static void splitByComma(String value, List<String> result) {
     protected SortedSet<String> getRequestedProjects(String paramName,
             String cookieName) {
         TreeSet<String> set = new TreeSet<>();
-        List<Project> projects = getEnv().getProjects();
+        HashSet<Project> projects = getEnv().getProjects();
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/web/PageConfig.java]: use supertype `Set`

File: src/org/opensolaris/opengrok/configuration/Project.java (hunk 1 above)
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/Project.java]: I see, this isn't possible with this setup.

Comment (vladak) [inline src/org/opensolaris/opengrok/configuration/Project.java]: I will try to convert it to HashMap, it will be better that way.

File: src/org/opensolaris/opengrok/index/Indexer.java (hunk 2 above)
Comment (vladak) [inline src/org/opensolaris/opengrok/index/Indexer.java]: It's not obvious to me why it is needed. Possibly for the entries to appear in lexicographic order in configuration.xml. If it's deemed to be necessary, we can always bring it back.

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java (hunk 6 above)
Comment (vladak) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: yep. bad Netbeans ! :-)

File: src/org/opensolaris/opengrok/index/Indexer.java (hunk 2 above)
Comment (tulinkry) [inline src/org/opensolaris/opengrok/index/Indexer.java]: We print them as sorted sets so this shouldn't be necessary after all. These changes were introduced in #1029 and before that PR we had had to sort the list of projects manually to display them. That seems like the original reason to me.

File: test/org/opensolaris/opengrok/configuration/ProjectTest.java [hunk 16]
```diff
@@ -113,15 +109,6 @@ public void testGetProject() {
         assertEquals(bar, Project.getProject("/foo-bar/ha.c"));
         assertNull(Project.getProject("/foof"));
         assertNull(Project.getProject("/foof/ha.c"));
-
-        // Make sure that the matching is not dependent on list ordering.
-        Collections.reverse(projects);
```
Comment (vladak) [inline test/org/opensolaris/opengrok/configuration/ProjectTest.java]: nothing to reverse now as projects are stored in HashMap

**Comment by vladak** [comment]
The conversion to `HashMap` of course changes the structure in `configuration.xml` so it will look like this:

```
  <void property="projects">
   <void method="put">
    <string>opengrok-test-mercurial-repo</string>
    <object class="org.opensolaris.opengrok.configuration.Project">
     <void property="name">
      <string>opengrok-test-mercurial-repo</string>
     </void>
     <void property="path">
      <string>/opengrok-test-mercurial-repo</string>
     </void>
    </object>
   </void>
...

The important property of this scheme is that the key of the map is the basename of the file entry under source root.
```

File: src/org/opensolaris/opengrok/configuration/Project.java [hunk 17]
```diff
@@ -53,6 +53,19 @@
      */
     private Set<Group> groups = new TreeSet<>();
 
+    // This empty constructor is needed for serialization.
+    public Project () {
+    }
+
+    public Project (String name) {
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/Project.java]: +1 for this

File: src/org/opensolaris/opengrok/configuration/Project.java [hunk 18]
```diff
@@ -215,16 +231,15 @@ public static Project getProject(File file) {
...
      */
     public static Project getByName(String name) {
-        Project ret = null;
         RuntimeEnvironment env = RuntimeEnvironment.getInstance();
         if (env.hasProjects()) {
-            for (Project proj : env.getProjects()) {
-                if (name.indexOf(proj.getName()) == 0) {
-                    ret = proj;
-                }
+            Project search = new Project(name);
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/Project.java]: unused variable?

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java [hunk 19]
```diff
@@ -395,21 +397,29 @@ public String getPathRelativeToSourceRoot(File file, int stripCount) throws IOEx
     }
 
     /**
-     * Do we have projects?
+     * Do we have some projects ?
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: any

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java [hunk 20]
```diff
@@ -395,21 +397,29 @@ public String getPathRelativeToSourceRoot(File file, int stripCount) throws IOEx
...
      *
      * @return true if we have projects
      */
     public boolean hasProjects() {
-        List<Project> proj = getProjects();
+        Set<String> proj = getProjects().keySet();
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: doesn't the `size` method return the number of mappings?

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java [hunk 21]
```diff
@@ -395,21 +397,29 @@ public String getPathRelativeToSourceRoot(File file, int stripCount) throws IOEx
...
         return (proj != null && !proj.isEmpty());
     }
 
     /**
-     * Get all of the projects
-     *
+     * Get list of projects
      * @return a list containing all of the projects (may be null)
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: will never be a null

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java [hunk 22]
```diff
@@ -395,21 +397,29 @@ public String getPathRelativeToSourceRoot(File file, int stripCount) throws IOEx
...
      */
-    public List<Project> getProjects() {
+    public List<Project> getProjectList() {
+        return new ArrayList<Project>(threadConfig.get().getProjects().values());
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: what if getProjects() return null?

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java (hunk 9 above)
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: map

File: src/org/opensolaris/opengrok/index/IndexDatabase.java [hunk 23]
```diff
@@ -164,7 +164,7 @@ static void updateAll(ExecutorService executor, IndexChangedListener listener) t
         List<IndexDatabase> dbs = new ArrayList<>();
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/index/IndexDatabase.java]: copyright

**Comment by tulinkry** [comment]
+ change all hashmaps to the super type `Map` for return values/local variables etc

**Comment by tulinkry** [comment]
+ file an enhancements for the groups for
 - using hashmap too
 - constructor friendliness

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java (hunk 9 above)
Comment (vladak) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: fixed

File: src/org/opensolaris/opengrok/configuration/Project.java (hunk 18 above)
Comment (vladak) [inline src/org/opensolaris/opengrok/configuration/Project.java]: fixed

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java (hunk 19 above)
Comment (vladak) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: fixed

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java (hunk 20 above)
Comment (vladak) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: fixed

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java (hunk 21 above)
Comment (vladak) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: fixed

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java (hunk 22 above)
Comment (vladak) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: I think it will never be null since the `Configuration` constructor has this:

```
setProjects(new HashMap<>());
```

File: src/org/opensolaris/opengrok/index/IndexDatabase.java (hunk 23 above)
Comment (vladak) [inline src/org/opensolaris/opengrok/index/IndexDatabase.java]: fixed

**Comment by vladak** [comment]
Tried to change all HashMaps to Map, filed #1555 for the Group constructor.

File: src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java (hunk 22 above)
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java]: ok

File: src/org/opensolaris/opengrok/configuration/Configuration.java [hunk 24]
```diff
@@ -572,12 +572,12 @@ public void setHandleHistoryOfRenamedFiles(boolean enable) {
...
 
-    public List<Project> getProjects() {
+    public Map<String,Project> getProjects() {
         return projects;
     }
 
-    public void setProjects(List<Project> projects) {
-        this.projects = projects;
+    public void setProjects(Map<String,Project> projects) {
+        this.projects = (HashMap<String, Project>) projects;
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/configuration/Configuration.java]: if you do it [here](https://github.com/OpenGrok/OpenGrok/pull/1543/files#r113946427) the this cast is not necessary

**Comment by tulinkry** [comment]
ok to me now
