### PR TITLE
logging exceptions in linkify + support urls without the hostname

### LINKED ISSUE #1508: Validate configuration for regexps/urls
When setting `userPage` or when setting some regexps in the configuration; the app should try to validate if the patterns/urls are valid and that they will not throw any unchecked exception. This is similar to the #1443 but it should be expanded to all problematic properities.

Also mentioned in [a comment here](https://github.com/OpenGrok/OpenGrok/pull/1506#discussion_r109160439).

### LINKED ISSUE #1515: log exceptions in linkifyPattern()
```
public static String linkifyPattern(String text, Pattern pattern, String name, String url) {
        try {
            String buildLink = buildLink(name, url, true);
            return pattern.matcher(text).replaceAll(buildLink);
        } catch (URISyntaxException | MalformedURLException ex) {
            return text;
        }
    }
```

the exception should be logged.

### LINKED ISSUE #1517: linkifyPattern() should accept not fully formed URIs
After the changes in cset 6611b858 such config stopped working:

```
  <void property="bugPage">
   <string>/cgi-bin/buglookup.pl?bug=</string>
  </void>
```

since `buildLink()` throws `MalformedURLException`.

To workaround it I used

```
  <void property="bugPage">
   <string>http://foo/cgi-bin/buglookup.pl?bug=</string>
  </void>
```

however I don't like it too much - having to include hostname makes the config less generic and cannot be moved between machines easily.

### PR DESCRIPTION
**Pull request by tulinkry**
fixes #1515
fixes #1517
also together with #1531 (**needs to be merged**) fixes #1508

### CODE REVIEW

File: src/org/opensolaris/opengrok/web/Util.java [hunk 1]
```diff
@@ -1513,7 +1513,48 @@ public static String linkifyPattern(String text, Pattern pattern, String name, S
...
+                StringBuffer prepUrl = req.getRequestURL();
+                if (!url.isEmpty()) {
+                    prepUrl.append('/').append(url);
+                }
+                return new URI(prepUrl.toString()).toString();
+            }
+            return url;
+        } catch (URISyntaxException ex) {
+            LOGGER.log(Level.INFO,
+                    String.format("Unable to convert given url part '%s' to complete url", url),
```
Comment (vladak) [inline src/org/opensolaris/opengrok/web/Util.java]: url -> URL

File: src/org/opensolaris/opengrok/web/Util.java [hunk 2]
```diff
@@ -1513,7 +1513,48 @@ public static String linkifyPattern(String text, Pattern pattern, String name, S
             String buildLink = buildLink(name, url, true);
             return pattern.matcher(text).replaceAll(buildLink);
         } catch (URISyntaxException | MalformedURLException ex) {
+            LOGGER.log(Level.INFO, "The given url '{0}' is not valid", url);
```
Comment (tulinkry) [inline src/org/opensolaris/opengrok/web/Util.java]: changed

File: src/org/opensolaris/opengrok/web/Util.java (hunk 1 above)
Comment (tulinkry) [inline src/org/opensolaris/opengrok/web/Util.java]: changed
